# Generated by Django 4.2.3 on 2023-07-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Updateinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, choices=[('Stock Market Live', 'Stock Market Live'), ('Angel Learning Stock Market', 'Angel Learning Stock Market'), ('Live Share Tips Free', 'Live Share Tips Free'), ('Stock Of The Day - Intraday, BTST, Positional', 'Stock Of The Day - Intraday, BTST, Positional'), ('Everyday Intraday Tips Stock Banknifty Option', 'Everyday Intraday Tips Stock Banknifty Option'), ('Rise Investing - Stock, Niffty, Banknifty, Options', 'Rise Investing - Stock, Niffty, Banknifty, Options'), ('Upstocks Varsity', 'Upstocks Varsity'), ('Everyday Intraday Tips', 'Everyday Intraday Tips'), ('Share Market Course', 'Share Market Course'), ('Stock Axis - Free Stock Tips', 'Stock Axis - Free Stock Tips'), ('Free Intraday Tips Stocks MCX F & O', 'Free Intraday Tips Stocks MCX F & O'), ('Share Market Gurukul', 'Share Market Gurukul'), ('Stock Market Free Tips', 'Stock Market Free Tips'), ('Free Intraday Trading Tips', 'Free Intraday Trading Tips'), ('Share Market Tips', 'Share Market Tips'), ('Free Tranding Tips - Stock Market, Nifty 50', 'Free Tranding Tips - Stock Market, Nifty 50'), ('Free Tips - Equity, Stock, BankNifty, Option MCX', 'Free Tips - Equity, Stock, BankNifty, Option MCX'), ('Share Tips - Live Share Market Tips', 'Share Tips - Live Share Market Tips'), ('Stock Watch - Free Stock Tips', 'Stock Watch - Free Stock Tips'), ('Free Intraday Tips', 'Free Intraday Tips'), ('Stock Market Course', 'Stock Market Course'), ('Dhan Intraday Tips - Stock, Nifty, Banknifty, Options', 'Dhan Intraday Tips - Stock, Nifty, Banknifty, Options'), ('HugeProfit_Share_Market_Tips', 'HugeProfit_Share_Market_Tips'), ('Intraday Tips', 'Intraday Tips'), ('Stock Market Pulse', 'Stock Market Pulse'), ('Free Currency Tips Stock Market', 'Free Currency Tips Stock Market'), ('Angel Learning Stock Market', 'Angel Learning Stock Market'), ('Live Share Tips Daily Free Stock Tips MCX Advisory', 'Live Share Tips Daily Free Stock Tips MCX Advisory'), ('Angel Varsity Free Stock Market Course And Tips', 'Angel Varsity Free Stock Market Course And Tips')], help_text='If App Name is not found. You have to add App Name in models File', max_length=255, null=True, unique=True)),
                ('current_version', models.CharField(blank=True, default='', help_text='for ex. 0.1 , 0.8, 2.0, 2.2 ', max_length=255, null=True)),
                ('maintenance_mode', models.CharField(default=False, help_text='Switch False to remove app popup blocker alert for users to this app', max_length=255, null=True)),
                ('Majortitle', models.CharField(blank=True, default='', help_text='App major update Title goes here', max_length=255, null=True)),
                ('Majormsg', models.CharField(blank=True, default='', help_text='App major update Message goes here', max_length=255, null=True)),
                ('Majorbtn', models.CharField(blank=True, default='', help_text='App major update Button Text goes here', max_length=255, null=True)),
                ('Minortitle', models.CharField(blank=True, default='', help_text='App minor update Title goes here', max_length=255, null=True)),
                ('Minormsg', models.CharField(blank=True, default='', help_text='App minor update Message goes here', max_length=255, null=True)),
                ('Minorbtn', models.CharField(blank=True, default='', help_text='App minor update Button Text goes here', max_length=255, null=True)),
                ('maintenance_title', models.CharField(blank=True, default='', help_text='maintenance Message goes here', max_length=255, null=True)),
                ('maintenance_msg', models.CharField(blank=True, default='', help_text='maintenance Message goes here', max_length=255, null=True)),
            ],
        ),
    ]
